### PR TITLE
Compare gold files with zcmp.

### PR DESCRIPTION
**Pull request by erikcorry**
This results in better compression (smaller gold files in the repo) and we are not dependent on the exact compression algorithm used, since the comparison takes place on the decompressed files.

### CODE REVIEW

**Comment by erikcorry** [comment]
Before vs. after:

-rw-r--r-- 1 erik erik 3758 Sep 29 18:55 tests/gold/drop_shadow_visualized.toit-000000.png.gz
-rw-r--r-- 1 erik erik 3138 Sep 29 18:55 tests/gold/drop_shadow_visualized.toit-000001.png.gz
-rw-r--r-- 1 erik erik 3276 Sep 29 18:55 tests/gold/drop_shadow_visualized.toit-000002.png.gz
-rw-r--r-- 1 erik erik 3148 Sep 29 18:55 tests/gold/drop_shadow_visualized.toit-000003.png.gz
-rw-r--r-- 1 erik erik 3168 Sep 29 18:55 tests/gold/drop_shadow_visualized.toit-000004.png.gz
-rw-r--r-- 1 erik erik 2999 Sep 29 18:55 tests/gold/drop_shadow_visualized.toit-000005.png.gz
$ git checkout origin/main
$ ls -al tests/gold/drop*
-rw-r--r-- 1 erik erik 22625 Sep 29 18:57 tests/gold/drop_shadow_visualized.toit-000000.png
-rw-r--r-- 1 erik erik  7817 Sep 29 18:57 tests/gold/drop_shadow_visualized.toit-000001.png
-rw-r--r-- 1 erik erik  9046 Sep 29 18:57 tests/gold/drop_shadow_visualized.toit-000002.png
-rw-r--r-- 1 erik erik  7818 Sep 29 18:57 tests/gold/drop_shadow_visualized.toit-000003.png
-rw-r--r-- 1 erik erik  8386 Sep 29 18:57 tests/gold/drop_shadow_visualized.toit-000004.png
-rw-r--r-- 1 erik erik  6779 Sep 29 18:57 tests/gold/drop_shadow_visualized.toit-000005.png

**Review by floitsch — APPROVED** [review]
LGTM, but this means that it's not (easily) possible to see the gold files during code reviews anymore.

**Comment by floitsch** [comment]
That said: Git has a way of only downloading a specific directory, so maybe we should just do that instead.

**Comment by erikcorry** [comment]
I'll be using pngcmp from the toit-png-tools directory instead.

**Pull request closed without merging**
